### ISSUE TITLE
Need version for father

### ISSUE THREAD

**Issue by Sequoia** [AllThingsSmitty/jquery-tips-everyone-should-know#5]
Are there any plans in the works to release a guide for fathers? Obviously this one won't work because the lessons all teach techniques that are helpful exclusively to moms and address uniquely female programming issues. TIA

**Comment by AllThingsSmitty** [comment]
@Sequoia a while back I had considered that, "CSS That Makes Your Dad Cool", etc., but I'm actually considering renaming this repo to something more appropriate, e.g., jQuery Protips, simply because I don't want my lame attempt to be funny or clever to in any way offend anyone. In hindsight, I probably should've done it from the beginning.

**Comment by AllThingsSmitty** [comment]
Addressed with https://github.com/AllThingsSmitty/jquery-tips-everyone-should-know/commit/a1250ed127eb298f384f8e5ce32a5c7d125279ba.

**Comment by filtercake** [comment]
@AllThingsSmitty after leaving a bit disturbed yesterday I came back to ask sth similar... very cool to see it already being changed :+1:

**Comment by Sequoia** [comment]
:+1:
